# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Shao Ren, PhD
# Description of the Site
description: I build creative Apps to serve the planet

# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: elvin.shaoxuan.ren@gmail.com
twitter_username: shaoxren
linkedin_username: shaoxuan-ren-850a93117
github_username:  shaoxuanren
youtube_channel_id: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: shaoren

# Name of the Author
author-name: Shao Ren
# URL for the Image of the Author
author-image: './utilis/profile.jpeg'
# 60 Words About the Author
author-about:  Hey! My name is Shao (he, him), and I'm currently a Master candidate in Computer Science at the University of Illinois Urbana-Champaign (UIUC). I'm a creative developer as well as a chemist. During my Ph.D. at the University of British Columbia, I researched Physical Chemistry and Robotic Chemistry, a combination of CS and chemistry! I have been fascinated by the power of CS in the past few years. Check out some papers I wrote/contributed to in my Google scholar. Now I'm very excited to join the developer community to make a better world! 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/shaoxuanren

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
